### ISSUE TITLE
configuring sudoers file

### ISSUE THREAD

**Issue by fabinca** [HEADLIGHTER/Born2BeRoot-42#1]
i think the original sudoers file should be configurated with visudo instead of creating a new one 
-> https://www.tecmint.com/sudoers-configurations-for-setting-sudo-in-linux/

**Comment by HEADLIGHTER** [comment]
I think we should keep our original files as is, if possible. Anyway, you can and have the right to do as you like.  I find it unimportant which file we use.  The main thing is that it works and works as intended.
