### ISSUE TITLE
Software selection update (GRUB not offered)

### ISSUE THREAD

**Issue by n4mr3g** [HEADLIGHTER/Born2BeRoot-42#2]
Debian 11.2.0:

SSH server wasn't marked by default.

GNOME now comes marked by default, which if I'm correct we shouldn't install it because it's a GUI.

**Comment by HEADLIGHTER** [comment]
Hi! I've looked into it on latest Debian 11.3.0-netinst and there's nothing like this. All is going step-by-step just like in guide.
Check your installer, the order of actions performed during the installation process and leave me feedback here please.

**Comment by n4mr3g** [comment]
You're right. It was a mistake from my side as I used a different Debian iso. Sorry for the mislead and thank you for your reply!
