### ISSUE TITLE
🙂

### ISSUE THREAD

**Issue by israeloriente** [HEADLIGHTER/Born2BeRoot-42#4]
1) su - -> root password -> apt install sudo
2) [$ adduser <yourusername> sudo] (yep, you should be in root)
3) [$ sudo reboot], then log in again
4) [$ sudo -v] -> password
5) [$ sudo addgroup user42]
6) [$ sudo adduser yourusername user42]
7) [$ sudo apt update]

to

1) su - -> root password -> apt install sudo
2) [$ **sudo** adduser <yourusername> sudo] (yep, you should be in root) // <---------------------
3) [$ sudo reboot], then log in again
4) [$ sudo -v] -> password
5) [$ sudo addgroup user42]
6) [$ sudo adduser yourusername user42]
7) [$ sudo apt update]

**Comment by HEADLIGHTER** [comment]
We already under root and can manage users and groups without sudo, isn't it?
